sounds = [
    "MP3_SFX_Birdsong",
    "MP3_SFX_Campfire",
    "MP3_SFX_Crickets",
    "MP3_SFX_Crows",
    "MP3_SFX_Inferno",
    "MP3_SFX_Owls",
    "MP3_SFX_Rain_Heavy",
    "MP3_SFX_Rain_Light",
    "MP3_SFX_Rain_On_Roof",
    "MP3_SFX_Rockslide_Big",
    "MP3_SFX_Rockslide_Small",
    "MP3_SFX_Seagulls",
    "MP3_SFX_Thunder_01",
    "MP3_SFX_Thunder_02",
    "MP3_SFX_Thunder_03",
    "MP3_SFX_Waterfalls",
    "MP3_SFX_Waves_Heavy",
    "MP3_SFX_Waves_Light",
    "MP3_SFX_Waves_Medium",
    "MP3_SFX_Whalesong",
    "MP3_SFX_Wind",
    "MP3_SND_Arctic",
    "MP3_SND_Badlands",
    "MP3_SND_Desert",
    "MP3_SND_Forest_At_Night",
    "MP3_SND_Grasslands",
    "MP3_SND_Oceans",
    "MP3_SND_Rainforest",
    "MP3_SND_Riverlands",
    "MP3_SND_Underwater",
    "MP3_SND_Volcano",
    "MP3_SND_Woodlands",
];
sel = 0;
view_top = 0;
playing = -1;   // handle of the currently playing sound instance
