#:schema ../../../.gm-schema/v1.json#layer
kind = "instances"
depth = 0

[[entries]]
id = "inst_menu"
object = "obj_menu"
x = 0.0
y = 0.0

[[entries]]
id = "inst_demo"
object = "obj_demo"
x = 0.0
y = 0.0
