#:schema ../../../.gm-schema/v1.json#layer

kind = "instances"
depth = 0

[[entries]]
id = "inst_rm_demo2_obj_gm_logo_0"
object = "obj_gm_logo"
x = 640.0
y = 360.0

[[entries]]
id = "inst_rm_demo2_obj_demo_0"
object = "obj_demo"
x = 0.0
y = 0.0
