#:schema ../../.gm-schema/v1.json#tileset

animation_speed = 15.0
animations = []
frame_data = []
output_border = 2
output_columns = 9
sprite = "sprTileset_Wood"
sprite_no_export = true
texture_group = "default"
tile_count = 81

[offset]
x = 0
y = 0

[autotile.default.tiles]
"ESW|" = 23
"ESW|SE" = 24
"ESW|SE,SW" = 26
"ESW|SW" = 25
"ES|" = 39
"ES|SE" = 40
"EW|" = 38
"E|" = 49
"NESW|" = 1
"NESW|NE" = 3
"NESW|NE,NW" = 4
"NESW|NE,NW,SE" = 8
"NESW|NE,NW,SE,SW" = 17
"NESW|NE,NW,SW" = 13
"NESW|NE,SE" = 7
"NESW|NE,SE,SW" = 16
"NESW|NE,SW" = 12
"NESW|NW" = 2
"NESW|NW,SE" = 6
"NESW|NW,SE,SW" = 15
"NESW|NW,SW" = 11
"NESW|SE" = 5
"NESW|SE,SW" = 14
"NESW|SW" = 10
"NES|" = 19
"NES|NE" = 20
"NES|NE,SE" = 22
"NES|SE" = 21
"NEW|" = 32
"NEW|NE" = 34
"NEW|NE,NW" = 35
"NEW|NW" = 33
"NE|" = 46
"NE|NE" = 47
"NSW|" = 28
"NSW|NW" = 30
"NSW|NW,SW" = 31
"NSW|SW" = 29
"NS|" = 37
"NW|" = 43
"NW|NW" = 44
"N|" = 50
"SW|" = 41
"SW|SW" = 42
"S|" = 48
"W|" = 51
"|" = 52

[separation]
h = 0
v = 0

[tile_size]
height = 256
width = 256

[[brushes]]
name = "r6c1"
width = 3
height = 3
tiles = [[55, 56, 57], [64, 65, 66], [73, 74, 75]]

[autotile.default]
template = "sides_47"
source = "template"
derived_with = "--from template --origin 0,1"
derived_by = "0.3.31"
