sounds = [
    "Keyboard_Click_1",
    "Keyboard_Click_2",
    "Keyboard_Click_3",
    "Mouse_Click_1",
    "Mouse_Click_2",
    "Mouse_Hover_1",
    "Mouse_Hover_2",
    "No_Button_1",
    "No_Button_2",
    "Pop_1",
    "Pop_2",
    "Popdown_1",
    "Popdown_2",
    "Popup_1",
    "Popup_2",
    "Power_Off_1",
    "Power_Off_2",
    "Power_On_1",
    "Power_On_2",
    "Slider_Move__Ascending__1",
    "Slider_Move__Ascending__2",
    "Slider_Move__Descending__1",
    "Slider_Move__Descending__2",
    "Swipe_Closed_1",
    "Swipe_Closed_2",
    "Swipe_Open_1",
    "Swipe_Open_2",
    "Task_Complete_1",
    "Task_Complete_2",
    "Task_Failed_1",
    "Task_Failed_2",
    "Timer_Tick_1",
    "Timer_Tick_2",
    "Window_Close_1",
    "Window_Close_2",
    "Window_Open_1",
    "Window_Open_2",
    "Yes_Button_1",
    "Yes_Button_2",
];
sel = 0;
view_top = 0;
playing = -1;   // handle of the currently playing sound instance
