#:schema ../../.gm-schema/v1.json#shader

[host]
kind = "transition"

[[uniform]]
name = "count"
label = "Count"
default = 10.0
max = 50.0

[[uniform]]
name = "smoothness"
label = "Smoothness"
default = 0.5
