#:schema ../../.gm-schema/v1.json#tileset

animation_speed = 15.0
animations = []
frame_data = []
output_border = 2
output_columns = 10
sprite = "spr_ground_snowbound"
sprite_no_export = true
texture_group = "default"
tile_count = 108

[offset]
x = 0
y = 0

[autotile.default]
template = "sides_47"

[autotile.default.tiles]
"ESW|" = [2, 29, 38, 65, 74, 101]
"ESW|SE" = [2, 29, 38, 65, 74, 101]
"ESW|SE,SW" = [2, 29, 38, 65, 74, 101]
"ESW|SW" = [2, 29, 38, 65, 74, 101]
"ES|" = [1, 37, 73]
"ES|SE" = [1, 37, 73]
"NESW|" = [14, 50, 86]
"NESW|NE" = [28, 64, 100]
"NESW|NE,NW" = [28, 64, 100]
"NESW|NE,NW,SE" = [28, 64, 100]
"NESW|NE,NW,SE,SW" = [28, 64, 100]
"NESW|NE,NW,SW" = [28, 64, 100]
"NESW|NE,SE" = [28, 64, 100]
"NESW|NE,SE,SW" = [28, 64, 100]
"NESW|NE,SW" = [28, 64, 100]
"NESW|NW" = [30, 66, 102]
"NESW|NW,SE" = [30, 66, 102]
"NESW|NW,SE,SW" = [30, 66, 102]
"NESW|NW,SW" = [30, 66, 102]
"NESW|SE" = [4, 40, 76]
"NESW|SE,SW" = [4, 40, 76]
"NESW|SW" = [6, 42, 78]
"NES|" = [13, 18, 49, 54, 85, 90]
"NES|NE" = [13, 18, 49, 54, 85, 90]
"NES|NE,SE" = [13, 18, 49, 54, 85, 90]
"NES|SE" = [13, 18, 49, 54, 85, 90]
"NEW|" = [5, 26, 41, 62, 77, 98]
"NEW|NE" = [5, 26, 41, 62, 77, 98]
"NEW|NE,NW" = [5, 26, 41, 62, 77, 98]
"NEW|NW" = [5, 26, 41, 62, 77, 98]
"NE|" = [25, 61, 97]
"NE|NE" = [25, 61, 97]
"NSW|" = [15, 16, 51, 52, 87, 88]
"NSW|NW" = [15, 16, 51, 52, 87, 88]
"NSW|NW,SW" = [15, 16, 51, 52, 87, 88]
"NSW|SW" = [15, 16, 51, 52, 87, 88]
"NW|" = [27, 63, 99]
"NW|NW" = [27, 63, 99]
"SW|" = [3, 39, 75]
"SW|SW" = [3, 39, 75]

[separation]
h = 0
v = 0

[tile_size]
height = 128
width = 128
