#:schema ../../.gm-schema/v1.json#tileset

animation_speed = 15.0
animations = []
frame_data = []
output_border = 2
output_columns = 2
sprite = "spr_tileset_water"
sprite_no_export = true
texture_group = "default"
tile_count = 3

[offset]
x = 0
y = 0

[separation]
h = 0
v = 0

[autotile.default]
template = "sides_47"
edges= { e = "open", s = "open", w = "open" }

[autotile.default.tiles]
"ESW|" = 1
"ESW|SE" = 1
"ESW|SE,SW" = 1
"ESW|SW" = 1
"ES|" = 1
"ES|SE" = 1
"EW|" = 1
"E|" = 1
"NESW|" = 2
"NESW|NE" = 2
"NESW|NE,NW" = 2
"NESW|NE,NW,SE" = 2
"NESW|NE,NW,SE,SW" = 2
"NESW|NE,NW,SW" = 2
"NESW|NE,SE" = 2
"NESW|NE,SE,SW" = 2
"NESW|NE,SW" = 2
"NESW|NW" = 2
"NESW|NW,SE" = 2
"NESW|NW,SE,SW" = 2
"NESW|NW,SW" = 2
"NESW|SE" = 2
"NESW|SE,SW" = 2
"NESW|SW" = 2
"NES|" = 2
"NES|NE" = 2
"NES|NE,SE" = 2
"NES|SE" = 2
"NEW|" = 2
"NEW|NE" = 2
"NEW|NE,NW" = 2
"NEW|NW" = 2
"NE|" = 2
"NE|NE" = 2
"NSW|" = 2
"NSW|NW" = 2
"NSW|NW,SW" = 2
"NSW|SW" = 2
"NS|" = 2
"NW|" = 2
"NW|NW" = 2
"N|" = 2
"SW|" = 1
"SW|SW" = 1
"S|" = 1
"W|" = 1
"|" = 1

[tile_size]
height = 128
width = 128
